### ISSUE TITLE
Plans for a new stable release?

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/fanciblock#17]
First of all: what a cool module!

There have been some important bugfixes lately, notably #4 (and related).
Is there a schedule yet for the next stable release?

Current stable release is somewhat dated (2015). A fresh release might prevent duplicate issues to pop up.

**Comment by docwilmot** [comment]
@indigoxela I've fixed a few bugs and will release soon if all goes well.

**Comment by stpaultim** [comment]
@docwilmot - I tested the "add a box" fix and it seems to work for me. Should we go ahead and cut a release. 

There is only one outstanding PR and I don't think it will work properly until @hosef get's the patch into core. (Also, he must resubmit it to the new default branch).

**Comment by stpaultim** [comment]
Just looking at this module for the Virtual User Group tomorrow. I had forgotten about the work we did a little over a year ago without releasing an update.

Also, noticing that a couple of important features are still broken. I'll try to find time to work on this now that we have reached feature freeze for 1.18,

**Comment by stpaultim** [comment]
@docwilmot - I'm going to take another look at this and see what needs to be done for the next release.

**Comment by stpaultim** [comment]
@docwilmot - You issued a new release back in April of 2022, but the new release is 1.x-1.0.1 and the previous release from 2015 is 1.x-1.1.0.

![image](https://user-images.githubusercontent.com/3144571/177227331-340b439c-b8d5-4d83-90da-1a0a62ac87e6.png)

I believe that this numbering is wrong, 1.x-1.1.0 is higher than 1.x-1.0.1. This might be why the OLD version is still showing up on the project page.

![image](https://user-images.githubusercontent.com/3144571/177227484-af94984f-81fa-4557-93af-ed094174d862.png)

**Comment by stpaultim** [comment]
I forgot that I'm technically a co-maintainer. I went ahead and deleted the old release and created a new one. 

I think the most recently release is now available on Backdropcms.org

![image](https://user-images.githubusercontent.com/3144571/177228600-0b5aadf6-3e49-452e-819e-44983e99b156.png)
