### ISSUE TITLE
Show FA icons in alphabetical order

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/fanciblock#9]
In the UI the user is able to select Font Awesome icons from a drop down list, but there are over a 100 icons and they are not listed in alphabetical order, making it very difficult to find a specific icon on the list.

**Comment by hosef** [comment]
I created a PR that should fix the issue.

**Comment by stpaultim** [comment]
Awesome! I wish I could quickly pull down a copy of the module with all PR's included for testing.

**Comment by stpaultim** [comment]
FYI - I tested this PR locally and it works as promised and I consider it a huge UI improvement for this module! Thanks @hosef !!!!

**Comment by stpaultim** [comment]
This feature is still not part of the official release. I'm creating documentation for "How to Build a Farmers Market Site" and using this module. But, some nice improvements in dev version are still not available. 

https://learn-backdrop.simplo.site/user-guide/building-a-farmers-market-site
